language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
  - "pypy3"
install:
  - pip install -r requirements.txt
services:
  - redis
script:
  - python -m unittest discover
dist: bionic
