"""Added CeleryTaskTypes table. Added CeleryTask table

Revision ID: 1435beac77f2
Revises: 5bbb5d6bd901
Create Date: 2020-04-03 03:11:05.316874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1435beac77f2'
down_revision = '5bbb5d6bd901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('celery_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['celery_task_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'type_id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('celery_scheduled')
    # ### end Alembic commands ###

    op.execute('''INSERT INTO celery_task_types (id, name)
                  VALUES (0, "ON_FIRST_MOVE_TIMED_OUT"),
                         (1, "ON_DISCONNECT_TIMED_OUT")''')
    #op.execute('''COMMIT''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_scheduled',
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('task_id')
    )
    op.drop_table('celery_tasks')
    op.drop_table('celery_task_types')
    # ### end Alembic commands ###
