"""Initial migration

Revision ID: 5bbb5d6bd901
Revises: 
Create Date: 2020-04-01 14:56:01.725575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbb5d6bd901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('k_factor', sa.Integer(), nullable=True),
    sa.Column('cur_game_id', sa.Integer(), nullable=True),
    sa.Column('in_search', sa.Boolean(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_white_pieces_id', sa.Integer(), nullable=True),
    sa.Column('user_black_pieces_id', sa.Integer(), nullable=True),
    sa.Column('fen', sa.String(), nullable=True),
    sa.Column('is_started', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_black_pieces_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_white_pieces_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('celery_scheduled',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_scheduled')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
