"""empty message

Revision ID: d53f237b0b10
Revises: a60e3687db4f
Create Date: 2020-03-26 20:39:40.221760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53f237b0b10'
down_revision = 'a60e3687db4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('in_search', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'in_search')
    # ### end Alembic commands ###
